### PR TITLE
Removed bucket names from secrets template

### PR DESCRIPTION
**Pull request by prashbnair**

### CODE REVIEW

**Review by dgpatelgit — COMMENTED** [review]
I want to understand the reason behind removal of bucket name, I don't think it solves any problem.
With empty bucket value also respective component deployment will fail, as we have struggled first time to bring up this components. Also, we don't deploy INSIGHT and Audit component by default, so this changes should not impact default deployment script.

**Comment by yzainee-zz** [comment]
@dgpatelgit i think the values are wrong. i removed all of these and my deployment worked just fine

**Comment by yzainee-zz** [comment]
as for bucket names, you can point them to the correct names yourself

**Comment by prashbnair** [comment]
@dgpatelgit Buckets need to be created in S3 and can then be added to the secret by the user. There is no reason for them to be declared in the secret.

**Comment by yzainee-zz** [comment]
@prashbnair agree

**Comment by dgpatelgit** [comment]
@prashbnair even bucket are created by new user as per KT videos with predefined naming conversions, so I thought this default value will work for new comers / new deployments without any change in bucket default values. But as we have faced some issue with this default values. I am OK with empty values.

**Review by dgpatelgit — APPROVED** [review]

**Comment by yzainee-zz** [comment]
@dgpatelgit Does the deploy script today create any non existing buckets in S3?

**Pull request merged**
